story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story6.urls')),
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.index, name='index'),
    path("add-peserta/<int:id>",views.add_peserta,name="add_peserta"),
    path("delete-peserta/",views.delete_peserta, name="delete_peserta"),
    path("add-kegiatan/",views.add_kegiatan, name="add-kegiatan"),
]

story6/models.py
from django.db import models

# Create your models here.

class Peserta(models.Model):
    name = models.TextField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class Kegiatan(models.Model):
    name = models.TextField(max_length=100, unique=True)
    peserta = models.ManyToManyField(Peserta, blank=True)

    def __str__(self):
        return self.name

story6/forms.py
from django import forms
from .models import Kegiatan, Peserta

class PesertaForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control",
        "placeholder" : "Nama Peserta"
    }), label = "")
    class Meta:
        model = Peserta
        fields = "__all__"

class KegiatanForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control w-50 text-center",
        "placeholder" : "Nama Kegiatan"
    }), label = "")
    class Meta:
        model = Kegiatan
        fields = [ 'name' ]

story6/views.py
from django.shortcuts import render, redirect, reverse
from .models import Peserta, Kegiatan
from .forms import PesertaForm, KegiatanForm

# Create your views here.
def index(request):
    context = {
        "kegiatans" : Kegiatan.objects.all(),
        "pesertaform" : PesertaForm,
    }
    return render(request, 'index.html', context)

def add_peserta(request,id):
    if request.method == "POST":
        kegiatan = Kegiatan.objects.get(id=id)
        nama = request.POST["name"]
        pesertabaru, baru = Peserta.objects.get_or_create(name=nama)
        
        if baru:
            pesertabaru.save()
            kegiatan.peserta.add(pesertabaru)
        else:
            try:
                kegiatan.peserta.get(name=nama)
            except:
                kegiatan.peserta.add(pesertabaru)

    return redirect(reverse("story6:index"))

def delete_peserta(request):
    if request.method == "POST":
        
        peserta = Peserta.objects.get(name = request.POST["name"])
        kegiatan = Kegiatan.objects.get(id = request.POST["kegiatan_id"])

        kegiatan.peserta.remove(peserta)

    return redirect("story6:index")

def add_kegiatan(request):
    if request.method == "POST":
        form_kegiatan = KegiatanForm(request.POST)

        if form_kegiatan.is_valid():
            form_kegiatan.save()

        return redirect(reverse("story6:index"))

    context = {
        "form_kegiatan" : KegiatanForm,
    }
    return render(request,"add-kegiatan.html",context)

story6/templates/add-kegiatan.html
{% extends 'base.html' %}{% load static %}
{% block content %}
<div class="addbox">
    <form class="d-flex justify-content-center align-items-center flex-column" action="{% url 'story6:add-kegiatan' %}" method="POST">
        <h3 class="tambah">Tambahkan Kegiatan</h3>
        {% csrf_token %}
        {{form_kegiatan}}
        <input class="btn btn-secondary mt-2" type="submit" value="Tambah Kegiatan">
    </form>
</div>
{% endblock %}

story6/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />

    <title>Event Keeper</title>
    <link rel="stylesheet" href="{% static 'style.css' %}" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-primary bg-warning fixed-top">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/add-kegiatan">Tambah Kegiatan</a>
          </li>
          <li class="nav-item"></li>
        </ul>
      </div>
    </nav>

      {% block content %} {% endblock %}
    
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

story6/templates/index.html
{% extends 'base.html' %}{% load static %}
{% block content %}
<div class="row px-2">
    {% for kegiatan in kegiatans %}
    <div class="col-lg-3 col-md-6 col-sm-12 konten">
        <div class="bg-secondary p-2 rounded-lg text-light d-flex justify-content-center align-items-center flex-column mb-3 border border-dark">
            <h3 class="card-content">{{kegiatan.name}}</h3>
            <h5>Peserta:</h5>
            <div class="overflow-auto name-list">
                <ol class="px-5">
                    {% for peserta in kegiatan.peserta.all %}
                        <li>
                            {{peserta.name}}
                            <form action="{% url 'story6:delete_peserta' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" value={{kegiatan.id}} name="kegiatan_id">
                                <button class="ml-1 px-1 text-light border-0 p-0 bg-danger d-inline" value="{{peserta.name}}" name="name" type="submit">X</button>
                            </form>
                        </li>
                    {% endfor %}
                </ol>
            </div>
            <div>
                <form action="{% url 'story6:add_peserta' id=kegiatan.id %}" method="POST" class="d-flex justify-content-center align-items-center flex-column mt-2">
                    {% csrf_token %}
                    {{pesertaform}}
                    <input class="btn btn-light mt-2" type="submit" value="Tambah Peserta">
                </form>
            </div>
        <div>
    </div>
</div>
</div>
    {% endfor %}
</div>
    
{% endblock %}